name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies (Server)
        working-directory: citesched_server
        run: dart pub get

      - name: Install Dependencies (Flutter)
        working-directory: citesched_flutter
        run: flutter pub get

      - name: Check All Formatting
        # This checks the root, client, flutter, and server folders
        run: dart analyze > analysis_report.txt || true