name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: |
          cd citesched_flutter && flutter pub get
          cd ../citesched_server && dart pub get

      - name: Run Flutter Tests
        working-directory: citesched_flutter
        run: flutter test

      - name: Run Server Tests
        working-directory: citesched_server
        run: dart test
