sonar.projectKey=Ashhh02_CITESched
sonar.organization=ashhh02
sonar.host.url=https://sonarcloud.io
sonar.sources=citesched_flutter/lib,citesched_server/lib
sonar.dart.analysis.reportPaths=analysis_report.txt
sonar.sourceEncoding=UTF-8

# Exclusions to stay under the line limit
sonar.exclusions=**/build/**, **/.dart_tool/**, **/android/**, **/ios/**, **/web/**, **/linux/**, **/macos/**, **/windows/**, citesched_flutter/test/**, citesched_server/test/**

# Disable C-family analysis
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-