sonar.projectKey=Ashhh02_PHP-FLUTTER

# This tells Sonar to look inside your specific folder
sonar.sources=New folder/flutter_client_php_backend

# Exclude large, non-code folders to keep the scan fast
sonar.exclusions=**/android/**, **/ios/**, **/.dart_tool/**, **/build/**, **/screenshots/**

# Language settings
sonar.language=php,dart
sonar.sourceEncoding=UTF-8